# Generated by Django 3.2.6 on 2021-11-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uctovnictvo', '0015_auto_20211123_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='dohoda',
            name='vynimka',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak si dohodár na túto dohodu uplatňuje odvodovú výnimku", max_length=3, null=True, verbose_name='Uplatnená výnimka'),
        ),
        migrations.AddField(
            model_name='historicaldobps',
            name='vynimka',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak si dohodár na túto dohodu uplatňuje odvodovú výnimku", max_length=3, null=True, verbose_name='Uplatnená výnimka'),
        ),
        migrations.AddField(
            model_name='historicaldopc',
            name='vynimka',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak si dohodár na túto dohodu uplatňuje odvodovú výnimku", max_length=3, null=True, verbose_name='Uplatnená výnimka'),
        ),
        migrations.AddField(
            model_name='historicaldovp',
            name='vynimka',
            field=models.CharField(choices=[('ano', 'Áno'), ('nie', 'Nie')], help_text="Uveďte 'Áno', ak si dohodár na túto dohodu uplatňuje odvodovú výnimku", max_length=3, null=True, verbose_name='Uplatnená výnimka'),
        ),
    ]
